p1=float(input ('Digite su nota del primer parcial '))
p2=float(input ('Digite su nota del segundo parcial '))
p3=float(input ('Digite su nota del tercer parcial '))
promediop=((p1+p2+p3)/3)
promedio=((promediop*55)/100)
efinal=float(input ('Digite su nota del examen final '))
examen=((efinal*30)/100)
tfinal=float(input ('Digite su nota del trabajo final '))
trabajo=((tfinal*15)/100)
notaf=(promedio+examen+trabajo)
print('Su nota final es: ',notaf)
